name: jaga_sehat
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^0.4.1   
  shared_preferences: "^0.4.2"  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  firebase_database: ^0.4.1
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/photo/20.jpg
   - assets/photo/42.jpg
   - assets/photo/54.jpg
   - assets/logo/logo1.png
   - assets/logo/logo2.png
   - assets/logo/logo3.png
   - assets/icon/fb.png
   - assets/icon/devs.png
   - assets/background/login_background.jpg
   - assets/literasi/title.jpg
   - assets/literasi/index.jpg
   - assets/literasi/greetings.jpg
   - assets/literasi/one.jpg
   - assets/literasi/two.jpg
   - assets/literasi/three.jpg
   - assets/literasi/four.jpg
   - assets/literasi/five.jpg
   - assets/pic/bpjs_jabar.jpg
   - assets/pic/bpjs_soreang.jpg
   - assets/pic/bpjs_bandung.jpg
   - assets/pic/bcs.png
   - assets/pic/bc_symbol.png
   - assets/pic/place_holder.jpg
   - assets/pic/yki.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Myriad-Pro
      fonts:
        - asset: assets/font/MyriadPro-Light.otf
    - family: Myriad-Reg
      fonts:
        - asset: assets/font/MyriadPro-Regular.ttf
    - family: Kelvetica
      fonts:
        - asset: assets/font/Kelvetica.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
